# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('account_id', models.CharField(max_length=10, primary_key=True)),
                ('account_number', models.CharField(max_length=15, primary_key=True)),
                ('accountee_name', models.CharField(max_length=100, primary_key=True)),
                ('account_type', models.CharField(max_length=10, primary_key=True)),
                ('ifsc_code', models.CharField(max_length=15, primary_key=True)),
                ('bank_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bank_city', models.CharField(max_length=50, primary_key=True)),
                ('bank_branch_name', models.CharField(max_length=100, primary_key=True)),
            ],
            options={
                'db_table': 'account_details_tbl',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category_tbl',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_address', models.CharField(max_length=200)),
                ('shop_area', models.CharField(max_length=100)),
                ('min_discount', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'shop_tbl',
            },
        ),
        migrations.CreateModel(
            name='ShopCategoryMapping',
            fields=[
                ('map_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Category')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Shop')),
            ],
            options={
                'db_table': 'shop_category_mapping_tbl',
            },
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('shopkeeper_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shopkeeper_name', models.CharField(max_length=100)),
                ('shopkeeper_email_id', models.CharField(max_length=50)),
                ('shopkeeper_phone_number', models.CharField(max_length=10)),
                ('shopkeeper_password', models.CharField(max_length=100)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Shop')),
            ],
            options={
                'db_table': 'shopkeeper_tbl',
            },
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='shopkeeper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Category'),
        ),
    ]
