# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20160201_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('account_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=15)),
                ('accountee_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=10)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_city', models.CharField(max_length=50)),
                ('bank_branch_name', models.CharField(max_length=100)),
                ('shopkeeper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Category')),
            ],
            options={
                'db_table': 'account_details_tbl',
            },
        ),
    ]
