# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_accountdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='shopkeeper_id',
        ),
        migrations.DeleteModel(
            name='AccountDetails',
        ),
    ]
